# Generated by Django 5.2.4 on 2025-08-09 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/', verbose_name='Флаг страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название умения')),
            ],
            options={
                'verbose_name': 'Умение',
                'verbose_name_plural': 'Умения',
            },
        ),
        migrations.CreateModel(
            name='TransferAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Приемущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='TransferWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название способа')),
                ('needed_sum', models.IntegerField(default=0, verbose_name='Необходимая сумма, $')),
                ('duration_days', models.IntegerField(default=0, verbose_name='Срок выполнения (в днях)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание способа переезда')),
                ('instantly', models.BooleanField(default=False, verbose_name='Моментально?')),
                ('is_legally', models.BooleanField(default=True, verbose_name='Легальный переезд?')),
                ('is_add_services', models.BooleanField(blank=True, default=False, null=True, verbose_name='Дополнительная услуга?')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='Страна переезда')),
                ('documents', models.ManyToManyField(blank=True, to='api.document', verbose_name='Необходимые документы')),
                ('skills', models.ManyToManyField(blank=True, to='api.skill', verbose_name='Необходимые навыки')),
            ],
            options={
                'verbose_name': 'Способ переезда',
                'verbose_name_plural': 'Способы переезда',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=100, verbose_name='Телеграм')),
                ('answers_json', models.JSONField(blank=True, null=True, verbose_name='Ответы с формы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_way', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transferway', verbose_name='Способ выезда')),
            ],
        ),
    ]
