# Generated by Django 5.2.4 on 2025-08-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Преимущество')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.AddField(
            model_name='transferway',
            name='advantages',
            field=models.ManyToManyField(blank=True, null=True, to='api.advantages', verbose_name='Преимущество'),
        ),
    ]
