# Generated by Django 5.2.4 on 2025-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='transferway',
            name='nelegal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Нелегальный переезд'),
        ),
        migrations.AddField(
            model_name='transferway',
            name='obuchnui',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Обычный переезд'),
        ),
        migrations.AddField(
            model_name='transferway',
            name='otsrochka',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отсрочка'),
        ),
    ]
