
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: myproject_backend
    volumes:
      - ./backend:/app:cached
      # Персистим sqlite файл локально
      - ./backend/db.sqlite3:/app/db.sqlite3
      # Общая точка для static и media
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    # SQLite не требует зависимостей, поэтому depends_on оставить пустым

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myproject_frontend
    ports:
      - "8080:80"   # nginx будет доступен на http://localhost:8080
    volumes:
      # скопированные в контейнер сборки будут в /usr/share/nginx/html
      # подключаем static_volume чтобы nginx мог отдавать Django static из backend
      - static_volume:/usr/share/nginx/html/backend_static:ro
      - media_volume:/usr/share/nginx/html/backend_media:ro

volumes:
  static_volume:
  media_volume:
