
services:
  backend:
    build: ./backend
    container_name: backend
    command: sh /code/start.sh
    volumes:
      - ./backend:/code
      - media:/code/media
    expose:
      - "8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    expose:
      - "80"

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media:/code/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

volumes:
  media:

